BaSP-TG-52: Standarize errors code
BaSP-a2022/ayom-b-trackgenix-app pull request #16
Opened 2022-11-05 23:49 UTC by GonzaloAsencio

Change "data.msg" to "data.message" in "index.js" on Project folder.

2022-11-06 20:56 UTC, Ignacio-Sormani requested changes

2022-11-06 20:56 UTC, Ignacio-Sormani commented on .vs/VSWorkspaceState.json
> +{
Don't push files under the .vs folder

2022-11-06 20:56 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
>        if (response.status === 200) {
It was a PUT method, so succesful response status should be 201

2022-11-06 20:56 UTC, Ignacio-Sormani commented on src/Components/Projects/List/index.js
>      if (response.status === 200) {
It was a DELETE method, so succesful response status should be 204

2022-11-07 23:47 UTC, Ignacio-Sormani approved these changes

2022-11-08 09:12 UTC, MaicolFreire001 approved these changes

2022-11-08 13:27 UTC, fede230298 commented on src/Components/Projects/Form/index.js
>        }
After this change, we could just make it into one else if.

2022-11-08 13:28 UTC, fede230298 commented on src/Components/Projects/List/index.js
>      }
Same as above

2022-11-08 13:57 UTC, fede230298 approved these changes

2022-11-08 19:24 UTC, merged