BaSP-TG-58: Timesheets improovements
BaSP-a2022/ayom-b-trackgenix-app pull request #18
Opened 2022-11-06 20:49 UTC by JuliMonte5

Added the following corrections according to QA suggestions:

- Default values are now shown when acceding the edit timesheet screen.
- Fixed alert shown when a timesheet is deleted.
- A failed attempt to create/edit a timesheet no longer redirects to timesheets page.
- The select item in create timesheet screen now shows a "choose one" placeholder.
- Added a confirmation modal before deleting a timesheet.

2022-11-06 20:58 UTC, Ignacio-Sormani commented
Fix typo in the name of the PR: "improovements"

2022-11-06 21:05 UTC, Ignacio-Sormani requested changes

2022-11-06 21:05 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +            --Choose and option--
Did you mean --Choose an option--?

2022-11-06 21:05 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +  switch (switcher) {
Just make an if statement for boolean values

2022-11-06 21:05 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +function Select({ defaultValue, switcher, Data, setId, field }) {
Use camelCase for props. It should be data

2022-11-06 21:05 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +          {Data.map((Item) => {
It should be item, no Item

2022-11-06 21:05 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +          {Data.map((Item) => {
It should be item, no Item

2022-11-07 00:13 UTC, Ignacio-Sormani requested changes

2022-11-07 00:13 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/index.js
>                    {TimeSheet.project.description}
Use timesheet instead of Timesheet

2022-11-07 00:13 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/index.js
> +        timeSheets={TimeSheets}
Is this 'TimeSheets' fine? Maybe you should use timeSheets

2022-11-07 00:13 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Select/index.js
> +    <select value={selected} onChange={(e) => handleChange(e)}>
Just a question. You are using `onChange={(e) => setId(e.target.value)}` inside the if but using `onChange={(e) => handleChange(e)}` in the second return. Is this ok?

2022-11-07 00:51 UTC, JuliMonte5 commented on src/Components/TimeSheets/Select/index.js
> +    <select value={selected} onChange={(e) => handleChange(e)}>
It is, this is because I don't want to use the setSelect on in that case, but since it shouldn't affect the functionality of this case I could use handleClick on both cases I guess

2022-11-07 02:41 UTC, Ignacio-Sormani approved these changes

2022-11-07 16:08 UTC, sofihoj approved these changes

2022-11-08 03:48 UTC, GonzaloAsencio approved these changes

2022-11-08 04:46 UTC, merged