BaSP-TG-65: Shared confirmation modal component
BaSP-a2022/ayom-b-trackgenix-app pull request #19
Opened 2022-11-07 04:51 UTC by GonzaloAsencio

- Create a shared confirmation modal component to confirm or decline an action.
- Required props that we need to consider: openModal, closeModal, title, warningText,confirmAction, declineButtonText, 
  confirmButtonText.
- Refactor in all the components where confirmation modals are being used with the new props structure.

2022-11-07 05:14 UTC, Ignacio-Sormani requested changes

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/index.js
> +  warningText,
I think it would be better to change the name prop from warningText to message

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/index.js
> +  return (
Leave a blank line between lines 23 and 24

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/modal.module.css
> +.moduleContainer {
Fix indentation in this file

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/modal.module.css
> +  .modalButtons > button {
Do not use html elements as part of css selectors

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/ListSuperAdmins/index.js
> +          warningText={`¿Are you sure you want to delete ${sAdmin.name}?`}
Don't write ¿ in the beginning on the question as it is not used in english

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Tasks/listItem.js
> +          warningText={`¿Are you sure you want to this task?`}
Don't write ¿ in the beginning on the question as it is not used in english

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Admins/adminRow.jsx
> +          warningText={`¿Are you sure you want to delete ${listAdmin.name}?`}
Don't write ¿ in the beginning on the question as it is not used in english

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Employees/Employee.js
> +            warningText={`¿Are you sure you want to delete ${employee.name}?`}
Don't write ¿ in the beginning on the question as it is not used in english

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/index.js
> +  openModal,
Maybe change openModal to showModal. What do you think?

2022-11-07 05:14 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/index.js
> +  declineButtonText,
declineButtonText and confirmButtonText could be optional and have  'Cancel' and 'Confirm' as default values.

To achieve this you should write the props like this:
```
declineButtonText = 'Cancel',
confirmButtonText = 'Confirm'
```

2022-11-07 05:16 UTC, Ignacio-Sormani commented
Maybe be could also add some logic to show the modal in loading mode while the request is fetching. Let's discuss this in the Demo meeting

2022-11-07 14:20 UTC, GonzaloAsencio commented on src/Components/Shared/Modal/index.js
> +  openModal,
It's true, it makes more sense

2022-11-07 19:00 UTC, GonzaloAsencio commented on src/Components/Shared/Modal/index.js
> +  warningText,
Oh, it is true.. Changed!

2022-11-07 23:03 UTC, Ignacio-Sormani approved these changes

2022-11-08 09:09 UTC, MaicolFreire001 requested changes

2022-11-08 09:09 UTC, MaicolFreire001 commented on src/Components/Tasks/listItem.js
> +          message={`Are you sure you want to this task?`}
This message seems wrong

2022-11-08 13:10 UTC, MaicolFreire001 approved these changes

2022-11-08 13:14 UTC, fede230298 approved these changes
SGMT 🚀

2022-11-08 19:39 UTC, sofihoj approved these changes

2022-11-09 00:16 UTC, merged