BaSP-TG-64: Shared modal component
BaSP-a2022/ayom-b-trackgenix-app pull request #20
Opened 2022-11-07 10:07 UTC by MaicolFreire001

**Shared modal component**
- Created a shared modal component for success and error messages
- Changed all modals for success and error messages with the newly created

2022-11-07 19:12 UTC, Ignacio-Sormani requested changes

2022-11-07 19:12 UTC, Ignacio-Sormani commented on src/Components/Shared/Modal/index.jsx
> +const Modal = ({ type, isOpen, message, handleClose, goBack }) => {
This modal should be a modal that just shows an error or success message, and a button to close it. I think we shouldn't use so many conditionals

2022-11-08 00:33 UTC, GonzaloAsencio approved these changes

2022-11-08 08:00 UTC, MaicolFreire001 commented on src/Components/Shared/Modal/shared.modal.module.css
> +.modalOverlay {
Done

2022-11-08 08:00 UTC, MaicolFreire001 commented on src/Components/Shared/Modal/shared.modal.module.css
> +.modalContent h3 {
Done

2022-11-08 08:00 UTC, MaicolFreire001 commented on src/Components/Shared/Modal/index.jsx
> +const Modal = ({ type, isOpen, message, handleClose, goBack }) => {
Modified

2022-11-08 08:01 UTC, MaicolFreire001 commented on src/Components/Admins/adminRow.jsx
> +    deleteAdmin(listAdmin._id);
Done

2022-11-08 08:01 UTC, MaicolFreire001 commented on src/Components/Admins/editAdminForm.jsx
> +  const [typeModal, setTypeModal] = useState();
Done

2022-11-08 13:13 UTC, fede230298 approved these changes
SGMT 🚀

2022-11-08 17:25 UTC, Ignacio-Sormani approved these changes

2022-11-08 21:58 UTC, JuliMonte5 approved these changes

2022-11-09 20:14 UTC, merged