BaSP-TG-57: confirmation-message-for-create-edit-SuperAdmin
BaSP-a2022/ayom-b-trackgenix-app pull request #21
Opened 2022-11-07 15:16 UTC by ProDIGGY-vinilos

Either when the user is creating or editing a super admin and has already completed the fields and press on the 'X' to go back to the super admins list, there could be a confirmation message for the user to approve this action or not.
Cause the user can have all the fields completed and press X by mistake and he suddenly loses all the info and has to start the filling all over again.

2022-11-07 23:06 UTC, Ignacio-Sormani commented
Change the name of the PR to "BaSP-TG-57: confirmation message for create and edit SuperAdmin"

2022-11-08 00:09 UTC, Ignacio-Sormani requested changes

2022-11-08 00:09 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/ListSuperAdmins/listSuperAdmins.module.css
> +
Remove this blank line

2022-11-08 00:09 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/ListSuperAdmins/index.js
>  const ListSuperAdmin = ({ sAdmin, onDeleteSuperAdmin }) => {
Change name of prop to superAdmin

2022-11-08 00:09 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/Form/index.js
> +        break;
Use return; instead of break;

Break should be used only in switches, return is a method of the functions

2022-11-08 00:09 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/super-admins.module.css
> +th {
Do not use html elements in css selectors, just use classes

2022-11-08 00:17 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/super-admins.module.css
> +th {
i made this hotfix only to see some things, im waiting the ticket to fix all the problems with styling or whatever the team decides

2022-11-08 00:28 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/ListSuperAdmins/listSuperAdmins.module.css
> +
Done

2022-11-08 00:29 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/ListSuperAdmins/index.js
>  const ListSuperAdmin = ({ sAdmin, onDeleteSuperAdmin }) => {
Done

2022-11-08 00:32 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/Form/index.js
> +        break;
Done, my bad, i wrote it unconsciously, i'm used to put the break to cut the function its a bad habit

2022-11-08 03:47 UTC, GonzaloAsencio approved these changes

2022-11-08 04:44 UTC, Ignacio-Sormani approved these changes

2022-11-08 04:45 UTC, Ignacio-Sormani commented
Resolve conflicts and then move the ticket to Ready for QA

2022-11-08 13:24 UTC, fede230298 approved these changes
SGTM 🚀

2022-11-08 16:52 UTC, merged