BaSP-TG-66: Shared confirmation modal component
BaSP-a2022/ayom-b-trackgenix-app pull request #24
Opened 2022-11-08 20:56 UTC by GonzaloAsencio

Create a shared datepicker component .
Refactor in all the components where selects are being used with the new props structure.
Required props that we need to consider: disabled.

2022-11-08 22:07 UTC, JuliMonte5 requested changes

2022-11-08 22:07 UTC, JuliMonte5 commented on src/Components/Shared/Modal/index.js
> +function Modal({
Should be an arrow function

2022-11-08 22:07 UTC, JuliMonte5 commented on src/Components/Shared/Modal/modal.module.css
> +    bottom: 0;
Duplicated properties

2022-11-09 00:54 UTC, ignacioaristo requested changes

2022-11-09 00:54 UTC, ignacioaristo commented on src/Components/Employees/Employee.js
>              title={'DELETE EMPLOYEE'}
move those message in a variable outside

2022-11-09 00:54 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +      //CAMBIAR ESTADO  200 por 201
remove this comment

2022-11-09 00:54 UTC, ignacioaristo commented on src/Components/Projects/List/index.js
> +        title={'DELETE PROJECT'}
move those message in a variable outside

2022-11-09 01:58 UTC, GonzaloAsencio commented on src/Components/Shared/Modal/index.js
> +function Modal({
Done

2022-11-09 01:59 UTC, GonzaloAsencio commented on src/Components/Shared/Modal/modal.module.css
> +    bottom: 0;
Done

2022-11-09 01:59 UTC, GonzaloAsencio commented on src/Components/Projects/Form/index.js
> +      //CAMBIAR ESTADO  200 por 201
Done

2022-11-09 14:17 UTC, fede230298 approved these changes

2022-11-09 15:29 UTC, Ignacio-Sormani requested changes

2022-11-09 15:29 UTC, Ignacio-Sormani commented on src/Components/Shared/Datepicker/index.js
> +      <input type="date" value={inputValue} onChange={(e) => HandleChange(e)}></input>
inputs need a name, that is sent through props, so it is easier to use it as a key when making a setState

2022-11-09 16:00 UTC, JuliMonte5 approved these changes

2022-11-09 17:36 UTC, fede230298 approved these changes

2022-11-09 23:34 UTC, Ignacio-Sormani approved these changes

2022-11-09 23:35 UTC, merged