WIP-BaSP-TG-62: Shared button component
BaSP-a2022/ayom-b-trackgenix-app pull request #25
Opened 2022-11-08 21:21 UTC by ProDIGGY-vinilos

Shared button (primary and secondary version) with their styles and a rounded version ready to implement

2022-11-09 15:22 UTC, Ignacio-Sormani requested changes

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/Shared/Button/primaryBtn.js
> +import React from 'react';
I see that the only difference between the two buttons is in the style. In this case it's better to have a single component called 'Button' and make a conditional to use one class or the other

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/Shared/Button/primaryBtn.js
> +  let history = useHistory();
history should be a const

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/Shared/Button/primaryBtn.js
> +  return (
Leave a blank line before the return

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/Shared/Button/primaryBtn.js
> +    if (props.href != undefined) {
Always use strict comparison !== or ===

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/Shared/Button/primaryBtn.module.css
> +    background-color: white;
Use hexa colors. For example: #FFFFFF or #000000

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/index.js
> +      <div className={styles.addBtn}>
Is there a way to just use the Button without wrapping it in a div?

2022-11-09 15:22 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/index.js
> +      <div className={styles.addBtn}>
Maybe adding the className to the button

2022-11-09 20:38 UTC, ProDIGGY-vinilos commented on src/Components/Shared/Button/primaryBtn.js
> +  let history = useHistory();
Done

2022-11-09 20:41 UTC, ProDIGGY-vinilos commented on src/Components/Shared/Button/primaryBtn.js
> +import React from 'react';
Done

2022-11-09 20:42 UTC, ProDIGGY-vinilos commented on src/Components/Shared/Button/primaryBtn.js
> +    if (props.href != undefined) {
Done

2022-11-09 21:06 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/index.js
> +      <div className={styles.addBtn}>
i been trying but i cant make the button stay at the right, adding the className  to the Button doesn't take effect, the only thing i think is to adding the styles direct into the rounded style

2022-11-09 21:10 UTC, ProDIGGY-vinilos commented on src/Components/Shared/Button/primaryBtn.js
> +  return (
Done

2022-11-09 21:13 UTC, ProDIGGY-vinilos commented on src/Components/Shared/Button/primaryBtn.module.css
> +    background-color: white;
Done

2022-11-10 16:14 UTC, fede230298 approved these changes

2022-11-10 17:33 UTC, Ignacio-Sormani approved these changes

2022-11-11 01:12 UTC, merged