BaSP-TG-95: Projects redux - Get
BaSP-a2022/ayom-b-trackgenix-app pull request #33
Opened 2022-11-11 21:04 UTC by GonzaloAsencio

- Create constants to get projects
- Create thunk to get projects
- Create projects reducer
- Create projects reducer
- Connect list component with store to get projects

2022-11-11 21:10 UTC, Ignacio-Sormani commented on src/redux/rootReducer.js
> +  Projects: ProjectsReducer
Use camel case for imports and store modules

2022-11-11 21:10 UTC, Ignacio-Sormani commented on src/Components/Projects/index.js
> +      <section className={styles.container}>
Use shared info modal

2022-11-11 22:34 UTC, GonzaloAsencio commented on src/redux/rootReducer.js
> +  Projects: ProjectsReducer
Done

2022-11-11 22:48 UTC, GonzaloAsencio commented on src/Components/Projects/index.js
> +      <section className={styles.container}>
Done

2022-11-12 09:14 UTC, MaicolFreire001 requested changes

2022-11-12 09:14 UTC, MaicolFreire001 commented on src/Components/Projects/index.js
> +  }
This implementation doesn't work, this throws [Uncaught Invariant Violation: Too many re-renders.] when an error occurs. 
You can check the code in the PR #80 for a solution

2022-11-12 14:05 UTC, GonzaloAsencio commented on src/Components/Projects/index.js
> +  }
Done

2022-11-12 15:24 UTC, fede230298 approved these changes

2022-11-12 16:23 UTC, Ignacio-Sormani commented on src/redux/rootReducer.js
> +  Projects: projectsReducer
Should be project to maintain the consistency

2022-11-12 16:49 UTC, GonzaloAsencio commented on src/redux/rootReducer.js
> +  Projects: projectsReducer
That's weird, I had changed it before

2022-11-12 17:04 UTC, GonzaloAsencio commented on src/redux/rootReducer.js
> +  Projects: projectsReducer
Done!

2022-11-12 17:11 UTC, fede230298 approved these changes

2022-11-12 19:48 UTC, MaicolFreire001 approved these changes

2022-11-12 20:58 UTC, merged