BaSP-TG-94: SuperAdmins redux - Get
BaSP-a2022/ayom-b-trackgenix-app pull request #37
Opened 2022-11-12 21:08 UTC by aletiscornia

- Create constants to get superAdmins.
- Create actions to get superAdmins.
- Create thunk to get superAdmins.
- Create superAdmins reducer.
- Connect list component with store to get employees.

2022-11-12 21:15 UTC, MaicolFreire001 requested changes

2022-11-12 21:15 UTC, MaicolFreire001 commented on src/Components/SuperAdmins/index.js
> +    );
You should use the messageModal here to display the error

2022-11-12 22:29 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +    );
fixed

2022-11-12 22:30 UTC, ProDIGGY-vinilos approved these changes

2022-11-12 22:56 UTC, fede230298 approved these changes

2022-11-13 01:29 UTC, GonzaloAsencio commented
Resolve Conflict

2022-11-13 07:34 UTC, MaicolFreire001 requested changes

2022-11-13 07:34 UTC, MaicolFreire001 commented on src/Components/SuperAdmins/index.js
> +  }
This impementation will throw an infinite render loop error. You can check how you can avoid that in the other entities that were merged

2022-11-13 17:27 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +  }
done

2022-11-13 18:51 UTC, MaicolFreire001 approved these changes

2022-11-13 20:44 UTC, GonzaloAsencio approved these changes

2022-11-13 20:44 UTC, merged