BaSP-TG-41: Admin
BaSP-a2022/ayom-b-trackgenix-app pull request #4
Opened 2022-11-01 02:08 UTC by GonzaloAsencio

**List Admin :**

- Retrieve the data from the data base and list all the admins.
- Create a list view where each item has a button to add, update and delete.

**Delete an admin:**

-  Delete an admin from the list.

**Create an admin:**

- Create the form view.
- Create a new admin.

**Update an admin:**

- Update an admin from the list.

2022-11-01 02:12 UTC, GonzaloAsencio commented
I use "setTimeout" for the warnings, because I don't finish on time.

2022-11-01 03:05 UTC, Ignacio-Sormani commented
Please resolve conflicts

2022-11-01 03:21 UTC, Ignacio-Sormani requested changes

2022-11-01 03:21 UTC, Ignacio-Sormani commented on .vscode/settings.json
> +{
I think you should remove this

2022-11-01 03:21 UTC, Ignacio-Sormani commented on package.json
> +    "cors": "^2.8.5",
We don't need cors for react app

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/Modal/modal.module.css
> +  }
Please leave a blank line between each css block

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/Modal/modalAdmin.jsx
> +  const onCloseModal = () => {
Also leave one blank line between functions

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/adminRow.jsx
> +  const onCloseModal = () => {
Instead of onCloseModal it could be called deleteAdmin

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/adminRow.jsx
> +  const onCloseModal = () => {
Use async await and remove useTimeout

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/adminRow.jsx
> +            <img src={`${process.env.PUBLIC_URL}/assets/images/iconEdit.svg`} />
We don't hace an env variable called PUBLIC_URL. Just use the string for now

Also, if you want to set a new env variable in react it should have a prefix: "REACT_APP_XXXX_XXXX"

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/adminRow.jsx
> +          <img src={`${process.env.PUBLIC_URL}/assets/images/iconTrash.svg`} />
Same comment as above

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/admins.module.css
> +
Remove this empty line

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/admins.module.css
> +
Just leave one empty line here

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +    const params = new URLSearchParams(window.location.search);
Change this to read the path param from window.location.pathname. You can look at the code merged in TG-50, file: "Projects/Form/index.js"

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +    const params = new URLSearchParams(window.location.search);
Same as above

2022-11-01 03:21 UTC, Ignacio-Sormani commented on src/Components/Admins/index.js
> +          <button>+</button>
Should not use a block element inside an inline element. Just don't use the button

2022-11-01 17:42 UTC, GonzaloAsencio commented on .vscode/settings.json
> +{
Fixed!

2022-11-01 17:42 UTC, GonzaloAsencio commented on package.json
> +    "cors": "^2.8.5",
Removed!

2022-11-01 17:43 UTC, GonzaloAsencio commented on src/Components/Admins/Modal/modal.module.css
> +  }
Done

2022-11-01 17:57 UTC, GonzaloAsencio commented on src/Components/Admins/Modal/modalAdmin.jsx
> +  const onCloseModal = () => {
Done

2022-11-01 18:14 UTC, GonzaloAsencio commented on src/Components/Admins/adminRow.jsx
> +            <img src={`${process.env.PUBLIC_URL}/assets/images/iconEdit.svg`} />
ohh i see. Fixed!

2022-11-01 18:14 UTC, GonzaloAsencio commented on src/Components/Admins/adminRow.jsx
> +          <img src={`${process.env.PUBLIC_URL}/assets/images/iconTrash.svg`} />
Fixed

2022-11-01 18:15 UTC, GonzaloAsencio commented on src/Components/Admins/admins.module.css
> +
Done

2022-11-01 18:15 UTC, GonzaloAsencio commented on src/Components/Admins/admins.module.css
> +
Done

2022-11-01 22:15 UTC, fede230298 reviewed
Is there a specific reason you are using Promises insted of Async Await when fetching?

2022-11-02 01:45 UTC, GonzaloAsencio commented
For nothing in particular.I did it at the beginning of the project and it stayed that way.

2022-11-02 18:59 UTC, fede230298 commented on src/Components/Admins/adminTable.jsx
> +        <span>There are no admin yet!</span>
Maybe you can invert the elements and put first the table and as only condition 
`{list.length ? (<table>...</table> : <span>There are no admin yet!</span>`

2022-11-02 19:22 UTC, GonzaloAsencio commented on src/Components/Admins/adminTable.jsx
> +        <span>There are no admin yet!</span>
Done!

2022-11-02 19:51 UTC, fede230298 approved these changes
SGTM 🚀

2022-11-03 03:06 UTC, Ignacio-Sormani requested changes

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Layout/index.js
> +    case 'admins-form':
Path should be admin-form

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Admins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/admins`)
Remove .then and .catch. You should just use async await

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +        setTimeout(() => {
Remove setTimeout

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +      fetch(url, options).then(async (response) => {
Remove .then. You should just use async await

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +      fetch(url, options).then(async (response) => {
Remove .then. You should just use async await

2022-11-03 03:06 UTC, Ignacio-Sormani commented on src/Components/Admins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/admins`)
Remove .then and .catch. You should just use async await

2022-11-03 03:59 UTC, GonzaloAsencio commented on src/Components/Layout/index.js
> +    case 'admins-form':
Changed!

2022-11-03 04:00 UTC, GonzaloAsencio commented on src/Components/Admins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/admins`)
Changed!

2022-11-03 04:00 UTC, GonzaloAsencio commented on src/Components/Admins/editAdminForm.jsx
> +        setTimeout(() => {
Removed

2022-11-03 04:03 UTC, GonzaloAsencio commented on src/Components/Admins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/admins`)
Removed

2022-11-03 04:14 UTC, GonzaloAsencio commented on src/Components/Admins/editAdminForm.jsx
> +      fetch(url, options).then(async (response) => {
done

2022-11-03 04:14 UTC, GonzaloAsencio commented on src/Components/Admins/editAdminForm.jsx
> +      fetch(url, options).then(async (response) => {
done

2022-11-03 14:57 UTC, Ignacio-Sormani approved these changes

2022-11-04 01:50 UTC, sofihoj approved these changes

2022-11-04 03:01 UTC, merged