BaSP-TG-99: Admins redux - Create, update and delete
BaSP-a2022/ayom-b-trackgenix-app pull request #40
Opened 2022-11-14 20:46 UTC by MaicolFreire001

**Admis:**

Create:
- Created constants to create an admin
- Created actions to create admin
- Created thunk to create admin
- Completed admins reducer with the logic to create
- Connected form component with store to create an admin

Update:
- Created constants to update an admin
- Created actions to update admin
- Created thunk to update admin
- Completed admins reducer with the logic to update an admin
- Connected form component with store to update an admin

Delete :
- Created constants to delete an admin
- Created actions to delete admin
- Created thunk to delete admin
- Completed admins reducer with the logic to delete an admin
- Connected form component with store to delete an admin

2022-11-15 14:23 UTC, ignacioaristo requested changes

2022-11-15 14:23 UTC, ignacioaristo commented on src/redux/admins/reducer.js
>          list: []
The list into the initial state is already an empty array

2022-11-15 14:23 UTC, ignacioaristo commented on src/redux/admins/reducer.js
> +        list: []
Remove all.

2022-11-15 14:35 UTC, MaicolFreire001 commented on src/redux/admins/reducer.js
>          list: []
Resolved

2022-11-15 14:35 UTC, MaicolFreire001 commented on src/redux/admins/reducer.js
> +        list: []
Done

2022-11-15 19:18 UTC, GonzaloAsencio approved these changes

2022-11-15 20:18 UTC, fede230298 commented on src/redux/admins/thunks.js
> +        if (response.error) {
Change the second .then response to data, in order to not repeat names and be clearer.

Repeat in all cases

2022-11-15 20:23 UTC, fede230298 approved these changes

2022-11-16 10:08 UTC, MaicolFreire001 commented on src/redux/admins/thunks.js
> +        if (response.error) {
Done

2022-11-16 19:55 UTC, ignacioaristo approved these changes

2022-11-17 00:14 UTC, fede230298 commented on src/redux/admins/reducer.js
> +        list: [...state.list, action.data],
You are adding a new item to the list. Lets change the item with .map

2022-11-17 00:44 UTC, Ignacio-Sormani commented on src/redux/admins/reducer.js
> +        list: [...state.list, action.data],
Use map method to update the list

2022-11-17 00:45 UTC, Ignacio-Sormani commented on src/redux/admins/actions.js
> +  GET_ADMINS_PENDING,
When you make a post, put or delete you are making changes into a single admin, so actions, constants, thunks, etc should be in singular. For example: POST_ADMIN_PENDING

2022-11-17 11:50 UTC, MaicolFreire001 commented on src/redux/admins/actions.js
> +  GET_ADMINS_PENDING,
Done

2022-11-17 12:56 UTC, MaicolFreire001 commented on src/redux/admins/reducer.js
> +        list: [...state.list, action.data],
Done

2022-11-17 12:56 UTC, MaicolFreire001 commented on src/redux/admins/actions.js
> +  GET_ADMINS_PENDING,
Done

2022-11-17 13:27 UTC, ProDIGGY-vinilos commented on src/redux/admins/reducer.js
> +        list: [...state.list.filter((task) => task._id !== action.payload)],
Let's update to use .map

2022-11-17 16:43 UTC, Ignacio-Sormani requested changes

2022-11-17 16:43 UTC, Ignacio-Sormani commented on src/redux/admins/reducer.js
> +        list: [...state.list, action.data],
I don't see this is resolved. Take a look at the PR that fede made and that is already merged

2022-11-17 16:49 UTC, MaicolFreire001 commented on src/redux/admins/reducer.js
> +        list: [...state.list, action.data],
You're right, I forgot to save. It's pushed now

2022-11-17 16:56 UTC, Ignacio-Sormani approved these changes

2022-11-17 18:13 UTC, sofihoj approved these changes

2022-11-17 18:21 UTC, merged