BaSP-TG-81-Super Admins redux-Create, Update and elete
BaSP-a2022/ayom-b-trackgenix-app pull request #43
Opened 2022-11-15 21:59 UTC by aletiscornia

2022-11-15 22:27 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/Form/index.js
> +  useEffect(async () => {
Remove "Async" in line 79

2022-11-15 22:27 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/Form/index.js
> +  useEffect(async () => {
Remove "Async" in line 91

2022-11-15 22:33 UTC, aletiscornia commented on src/Components/SuperAdmins/Form/index.js
> +  useEffect(async () => {
done

2022-11-15 22:33 UTC, aletiscornia commented on src/Components/SuperAdmins/Form/index.js
> +  useEffect(async () => {
done

2022-11-16 02:20 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/Form/index.js
> +  const updateCreateSuperAdmin = async (url) => {
Move this logic inside the onConfirm function. Keep in mind that you are making this function async but there is no await

2022-11-16 21:00 UTC, ProDIGGY-vinilos commented on src/redux/superAdmins/actions.js
> +  DELETE_SUPERADMINS_ERROR
All of these should be singular like POST_SUPERADMIN_PENDING because you post , put and delete only 1 superadmin, and this is the same for methods in thunk, constant and actions

2022-11-16 21:01 UTC, ProDIGGY-vinilos commented on src/redux/superAdmins/thunks.js
> +              dispatch(deleteSuperAdminsError(err.toString()));
Check err, in other methods you use error instead of err

2022-11-16 23:35 UTC, Ignacio-Sormani commented on src/redux/superAdmins/reducer.js
> +        list: [...state.list, action.payload]
This is not updating the list, it is just adding the superadmin. Take a look at fede's PR to make this with a filter method

2022-11-17 00:16 UTC, fede230298 commented on src/redux/superAdmins/reducer.js
> +        list: [...state.list, action.payload]
Let's update it to use .map

2022-11-17 04:15 UTC, aletiscornia commented on src/redux/superAdmins/actions.js
> +  DELETE_SUPERADMINS_ERROR
done

2022-11-17 04:17 UTC, aletiscornia commented on src/redux/superAdmins/thunks.js
> +              dispatch(deleteSuperAdminsError(err.toString()));
done

2022-11-17 04:24 UTC, aletiscornia commented on src/redux/superAdmins/reducer.js
> +        list: [...state.list, action.payload]
fixed

2022-11-17 04:33 UTC, aletiscornia commented on src/Components/SuperAdmins/Form/index.js
> +  const updateCreateSuperAdmin = async (url) => {
done

2022-11-17 13:34 UTC, ProDIGGY-vinilos approved these changes

2022-11-17 17:23 UTC, fede230298 commented on src/redux/superAdmins/constant.js
> +export const GET_SUPERADMIN_ERROR = 'GET_SUPERADMIN_ERROR';
This should be in plural, as it gets all superadmins, the others are OK to be in singular

2022-11-17 17:35 UTC, MaicolFreire001 requested changes

2022-11-17 17:35 UTC, MaicolFreire001 commented on src/Components/SuperAdmins/index.js
> +  const onDeleteSuperAdmins = (id) => {
This shouldn't be in plural

2022-11-17 17:35 UTC, MaicolFreire001 commented on src/Components/SuperAdmins/index.js
> +            deleteItem={onDeleteSuperAdmins}
Same as above

2022-11-17 17:58 UTC, aletiscornia commented on src/redux/superAdmins/constant.js
> +export const GET_SUPERADMIN_ERROR = 'GET_SUPERADMIN_ERROR';
done

2022-11-17 17:58 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +  const onDeleteSuperAdmins = (id) => {
done

2022-11-17 17:59 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +            deleteItem={onDeleteSuperAdmins}
done

2022-11-17 18:03 UTC, MaicolFreire001 approved these changes
SGTM🚀

2022-11-17 18:18 UTC, ProDIGGY-vinilos commented on src/redux/superAdmins/constant.js
> +export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMIN_ERROR';
You made the string singular in the GET, make this plural

2022-11-17 18:18 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/index.js
> +import { getSuperAdmin, deleteSuperAdmin } from '../../redux/superAdmins/thunks';
Here the get is getSuperAdmins

2022-11-17 18:18 UTC, ProDIGGY-vinilos commented on src/Components/SuperAdmins/index.js
> +    dispatch(getSuperAdmin());
here too

2022-11-17 18:34 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +import { getSuperAdmin, deleteSuperAdmin } from '../../redux/superAdmins/thunks';
done

2022-11-17 18:34 UTC, aletiscornia commented on src/Components/SuperAdmins/index.js
> +    dispatch(getSuperAdmin());
done

2022-11-17 18:36 UTC, aletiscornia commented on src/redux/superAdmins/constant.js
> +export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMIN_ERROR';
done

2022-11-17 18:36 UTC, fede230298 approved these changes

2022-11-17 18:38 UTC, ProDIGGY-vinilos approved these changes

2022-11-17 19:28 UTC, GonzaloAsencio approved these changes

2022-11-17 23:23 UTC, ignacioaristo approved these changes

2022-11-18 02:45 UTC, sofihoj approved these changes

2022-11-18 04:05 UTC, merged