BaSP-TG-43: Projects Views and Methods with React
BaSP-a2022/ayom-b-trackgenix-app pull request #5
Opened 2022-11-01 23:31 UTC by fede230298

**List Projects:**

- Retrieve Projects data from data base
- Create a Table view where the information is shown
- Add three buttons, to add, to delete and to edit

**Delete Projects**

- Delete a Project from the data base

**Create a Project**

- Form view to complete and POST a new Project, with the employees from the data base

**Update a Project**

- Form view to edit and PUT an existing Project, loading the data from the desired Project and loading it into the inputs

2022-11-02 00:28 UTC, Ignacio-Sormani requested changes

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/FormEmployees/index.js
> +        {eachEmployee ? (
If it's possible avoid big conditionals if they will return similar stuff

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +  }, [idState]);
Don't use states inside of useEffect parameters if you are changing its value inside of itself. Also, if idState changes it means that the page was reloaded with a different path params which implies that useEffect will be executed

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +  const [fetched, setFectched] = useState('');
const [isFetched, setIsFetched] = useState(false);

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +        setFectched('true');
'true' is not boolean, just use true or false

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +        console.error(error);
Remove console.log

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +    if (projectId === 'project-form') {
Just do an else from previous if

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +      setFectched('false');
'false' is not boolean, just use true or false

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +  const onChangeNameValue = (e) => {
You can probably do one function to update the state on all input changes using the name of the input that changed

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +      {fetched === 'true' && <h2>Edit Project</h2>}
You can make a conditional here:
`<h2>{`${isFetched ? 'Edit' : 'Add New'} Project`</h2>`

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +                name=""
name should not be empty

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +                id=""
Is id necessary?

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +                    eachEmployee={employee}
Maybe use employee instead of eachEmployee

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +              <input type="text" on onChange={onChangeNameValue} />
'on' should not be there

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +                name=""
Same as above for name and id

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/List/index.js
> +const List = ({ projectItem, onDeleteItem }) => {
If this is the List of employee use EmployeeList as name of the component

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/List/index.js
> +  const urlId = `/project-form/${projectItem._id}`;
You only use urlId one, there is no need to store it in a const

2022-11-02 00:28 UTC, Ignacio-Sormani commented on src/Components/Projects/List/index.js
> +    if (response.status === 200) {
Group responses if the functionality is the same. You can also do
`if ([404, 500].includes(response.status))`

2022-11-02 00:34 UTC, fede230298 commented on src/Components/Layout/index.js
> +      currentScreen = <ProjectForm text={'Submit'} />;
Yes, it is a leftover from a previous version of the ProjectForm, will be deleted.

2022-11-02 00:34 UTC, fede230298 commented on src/Components/Projects/Employees/index.js
> +const Employee = ({ employee }) => {
Will do

2022-11-02 00:35 UTC, fede230298 commented on src/Components/Projects/Employees/index.js
> +    <td key={employee._id}>
Will think how to replace it

2022-11-02 00:35 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +              if (singleEmployee._id === eachEmployee.employee) {
That was what I originally wanted to do, but couldn't figure it out

2022-11-02 01:47 UTC, GonzaloAsencio commented on src/Components/Projects/Form/FormEmployees/index.js
> +  /* deleteEmployee */
Delete this comment

2022-11-02 01:47 UTC, GonzaloAsencio commented on src/Components/Projects/Form/FormEmployees/index.js
> +      {/* <button onClick={deleteEmployee}>Delete Employee</button> */}
delete this comment

2022-11-02 01:50 UTC, GonzaloAsencio commented on src/Components/Projects/projects.module.css
> +
remove space on line 61

2022-11-02 02:01 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +              if (singleEmployee._id === eachEmployee.employee) {
If I write the prop like that, it wont render

2022-11-02 02:04 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +  }, [idState]);
Updated!

2022-11-02 02:08 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +        setFectched('true');
Updated, I did it like this before, but didn't work. Tried now and works. Odd

2022-11-02 02:09 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +        console.error(error);
Removed, leftover from debugging

2022-11-02 02:10 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +    if (projectId === 'project-form') {
Updated!

2022-11-02 02:10 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +      setFectched('false');
Updated

2022-11-02 03:28 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +  const onChangeNameValue = (e) => {
Done!

2022-11-02 03:28 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +      {fetched === 'true' && <h2>Edit Project</h2>}
Done!

2022-11-02 03:31 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +                    eachEmployee={employee}
Done!

2022-11-02 03:31 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +              <input type="text" on onChange={onChangeNameValue} />
Thanks! that was causing an error in the console

2022-11-02 03:34 UTC, fede230298 commented on src/Components/Projects/List/index.js
> +const List = ({ projectItem, onDeleteItem }) => {
This is the Project List, I'll name it ProjectList

2022-11-02 03:35 UTC, fede230298 commented on src/Components/Projects/List/index.js
> +  const urlId = `/project-form/${projectItem._id}`;
Done!

2022-11-02 12:37 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +      {/* <button onClick={deleteEmployee}>Delete Employee</button> */}
Done!

2022-11-02 12:37 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +  /* deleteEmployee */
Done!

2022-11-02 12:41 UTC, fede230298 commented on src/Components/Projects/List/index.js
> +    if (response.status === 200) {
Done with the ones with the same alert!

2022-11-02 12:42 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +                name=""
Deleted!

2022-11-02 12:43 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +                id=""
No, erased it

2022-11-02 12:43 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +                name=""
Completed!

2022-11-02 13:19 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +  const onChangeNameValue = (e) => {
Solved. I made one single function, where you pass a key to change, and the value through e.target.value. And it can receive a third argument which is a boolean. if one passes TRUE, it means it is changing the value of an employee, if you dont pass nothing, it means you are changing a Key outside of employee
`const onChangeValue = (key, value, keyArray = false) => {
    if (keyArray) {
      setProjectBody({
        ...projectBody,
        employees: [{ ...projectBody.employees[0], [key]: value }]
      });
    } else {
      setProjectBody({ ...projectBody, [key]: value });
    }
  };`

2022-11-02 13:21 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +  const [fetched, setFectched] = useState('');
Done!

2022-11-02 13:41 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +        {eachEmployee ? (
I don't know how to change this conditional. It is used to load a value from a fetch a save it into one of the options, and if not, just load the options without the selected button, and to do so, first I need to check whether it has or not an employee loaded. if it has, it maps through the values and see if one of the existent values matches the one loaded before, if so, it is selected, if not it is just loaded. And if it has no employee loaded, it just maps the options. That´s why i don´t know exactly how to reduce this. 
This point is related to the previous one, with the SELECTED prop. this way i can put the selected prop inside, if i do the way you proposed it wont work, on the other hand React proposes that instead of using select inside the option, I should use Value= on the Select tag directly. The problem there is that I cannot map the employees there, because I will have lots of selects with options and not just one select with all the options

2022-11-02 14:30 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +        {eachEmployee ? (
Something like this is reduced and works.
What I did was to change the position of the first condition (renamed as employee as sugested) into the if where it compares the ids, thus resulting in a way shorter version

`<div>
        <label>Employee: </label>
        <select onChange={(e) => changeValue('employee', e.target.value, true)}>
          <option value="" className={styles.displayNone} selected></option>
          {employees.map((singleEmployee) => {
            return (
              <option
                value={singleEmployee._id}
                key={singleEmployee._id}
                selected={employee && singleEmployee._id === employee.employee ? true : undefined}
              >
                {singleEmployee.lastName}
              </option>
            );
          })}
        </select>
      </div>`

2022-11-02 14:30 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +              if (singleEmployee._id === eachEmployee.employee) {
I found the problem
I had to make the condition like this

`selected={employee && singleEmployee._id === employee.employee ? true : undefined}`

2022-11-02 17:21 UTC, Ignacio-Sormani requested changes

2022-11-02 17:21 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/FormEmployees/index.js
> +                selected={employee && singleEmployee._id === employee.employee ? true : undefined}
Does it work if you write:
`selected={employee && singleEmployee._id === employee.employee}`

If it doesn't, try:
selected={!!(employee && singleEmployee._id === employee.employee)}`

2022-11-02 17:21 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/FormEmployees/index.js
> +                selected={employee && role === employee.role ? true : undefined}
Use same logic than comment for exployee select

2022-11-02 17:21 UTC, Ignacio-Sormani commented on src/Components/Projects/Form/index.js
> +        window.location.href = document.location.href = '/projects';
How does it work? Does it work if you just write `document.location.href = '/projects';`?

2022-11-02 17:21 UTC, Ignacio-Sormani commented on src/Components/Projects/index.js
> +      {projects.length > 0 ? (
You can just do `{projects.length ? (`

2022-11-02 18:32 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +                selected={employee && singleEmployee._id === employee.employee ? true : undefined}
Solved! worked just fine! Seems that with the employee conditional inside works

2022-11-02 18:33 UTC, fede230298 commented on src/Components/Projects/Form/FormEmployees/index.js
> +                selected={employee && role === employee.role ? true : undefined}
Same as above! Resolved!

2022-11-02 18:35 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +        window.location.href = document.location.href = '/projects';
Yes, it worked! Changed

2022-11-02 18:38 UTC, fede230298 commented on src/Components/Projects/Form/index.js
> +  const onChangeValue = (key, value, keyArray = false) => {
It means that if keyArray is not present when I call the function, the default value will be false, otherwise you should use true as third argument

When i change some key that is not in the array of employees, i just send the key and the value, but when used to change the ones that are from the array employees, i send the key, the value and true as third argument to make sure it modifies the correct key-value from the array

2022-11-02 18:39 UTC, fede230298 commented on src/Components/Projects/index.js
> +      {projects.length > 0 ? (
Yes, corrected!

2022-11-02 18:56 UTC, JuliMonte5 approved these changes

2022-11-02 19:16 UTC, GonzaloAsencio approved these changes

2022-11-03 03:11 UTC, Ignacio-Sormani approved these changes

2022-11-03 03:16 UTC, merged