BaSP-TG-114: Employee form update
BaSP-a2022/ayom-b-trackgenix-app pull request #50
Opened 2022-11-19 22:48 UTC by ProDIGGY-vinilos

Update the logic in the employee entity to use rect hook form and have joi validations

-  How to test:
- [ ] Check if the employee entity works properly, all inputs have the corrects validations and the errors are displayed correctly

2022-11-19 22:55 UTC, MaicolFreire001 requested changes

2022-11-19 22:55 UTC, MaicolFreire001 commented on src/Components/Employees/EmployeeForm.js
> +            label="Namea"
You misspelled here

2022-11-19 22:56 UTC, ProDIGGY-vinilos commented on src/Components/Employees/EmployeeForm.js
> +            label="Namea"
Uh, sorry i added that to see the input with that identation, done

2022-11-19 22:58 UTC, MaicolFreire001 approved these changes
SGTM🚀

2022-11-19 23:49 UTC, ignacioaristo requested changes

2022-11-19 23:49 UTC, ignacioaristo commented on src/Components/Employees/validation.js
> +    .required(),
custom the message of this validation

2022-11-19 23:49 UTC, ignacioaristo commented on src/Components/Employees/EmployeeForm.js
> +  const MOCK_DATA = {
Change this name, this is not a data mocked. Is real data

2022-11-19 23:52 UTC, JuliMonte5 approved these changes

2022-11-20 00:12 UTC, Ignacio-Sormani commented on src/Components/Employees/EmployeeForm.js
> +  const MOCK_DATA = {
Also it should be in camelCase

2022-11-20 18:45 UTC, ProDIGGY-vinilos commented on src/Components/Employees/EmployeeForm.js
> +  const MOCK_DATA = {
Sorry, i followed the class too literally

2022-11-20 19:12 UTC, ProDIGGY-vinilos commented on src/Components/Employees/validation.js
> +    .required(),
Done

2022-11-20 19:13 UTC, ProDIGGY-vinilos commented on src/Components/Employees/EmployeeForm.js
> +  const MOCK_DATA = {
done

2022-11-20 23:30 UTC, sofihoj approved these changes

2022-11-21 01:20 UTC, Ignacio-Sormani commented on src/Components/Employees/validation.js
> +export const schema = Joi.object({
We should have messages for every input

2022-11-21 16:43 UTC, ProDIGGY-vinilos commented on src/Components/Employees/validation.js
> +export const schema = Joi.object({
Done

2022-11-21 17:12 UTC, ignacioaristo approved these changes

2022-11-21 17:12 UTC, merged