BaSP-TG-112: Admin form update
BaSP-a2022/ayom-b-trackgenix-app pull request #51
Opened 2022-11-19 22:51 UTC by GonzaloAsencio

Replace the actual logic for react hook form logic
Add joi validations

2022-11-19 23:07 UTC, MaicolFreire001 approved these changes
SGTM🚀

2022-11-19 23:46 UTC, JuliMonte5 commented on src/Components/Admins/editAdminForm.jsx
> +            MOCK_DATA = {
you should do this in a useEffect with a hook that checks for the data to be updated, right now if you are in the edit page and you refresh it (which is the case covered by this fetch) the data in mocked data is not set (the fields get cleared)

2022-11-19 23:51 UTC, ignacioaristo requested changes

2022-11-19 23:51 UTC, ignacioaristo commented on src/Components/Admins/validations.jsx
> +import Joi from 'joi';
custom all the validation messages.

2022-11-19 23:51 UTC, ignacioaristo commented on src/Components/Admins/editAdminForm.jsx
> +  let MOCK_DATA = {
Change this variable name, this is not mocked, this is real data

2022-11-20 00:10 UTC, Ignacio-Sormani commented on src/Components/Admins/editAdminForm.jsx
> +  let MOCK_DATA = {
Also it should be in camelCase. And should probably be a const and not a let

2022-11-20 02:05 UTC, GonzaloAsencio commented on src/Components/Admins/editAdminForm.jsx
> +  let MOCK_DATA = {
i forgot to change it before doing the push.Done

2022-11-20 02:50 UTC, GonzaloAsencio commented on src/Components/Admins/editAdminForm.jsx
> +            MOCK_DATA = {
done

2022-11-20 02:50 UTC, GonzaloAsencio commented on src/Components/Admins/validations.jsx
> +import Joi from 'joi';
done

2022-11-20 03:06 UTC, JuliMonte5 approved these changes

2022-11-20 16:36 UTC, ignacioaristo approved these changes

2022-11-20 18:21 UTC, sofihoj approved these changes

2022-11-20 18:22 UTC, merged