BaSP-TG-115: Project form update
BaSP-a2022/ayom-b-trackgenix-app pull request #53
Opened 2022-11-20 20:16 UTC by MaicolFreire001

**What's have been done:**
- Replaced the actual logic for react hook form logic
- Added joi validations and error messages

**How to test:**
Check if the project entity works properly, all inputs have the corrects validations and the errors are displayed correctly
**Important note:** The role field doesn't show its error but it works fine, this issue will be resolved later.

2022-11-20 22:44 UTC, ignacioaristo submitted a review, later dismissed

2022-11-20 22:44 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +        fetch(`${process.env.REACT_APP_API_URL}/projects/${projectId}`)
If we are goin to handle an async external call, we should handle it into the thunks.

2022-11-21 15:04 UTC, MaicolFreire001 commented on src/Components/Projects/Form/index.js
> +        fetch(`${process.env.REACT_APP_API_URL}/projects/${projectId}`)
Done

2022-11-21 16:54 UTC, JuliMonte5 requested changes

2022-11-21 16:54 UTC, JuliMonte5 commented on src/Components/Projects/Form/index.js
> +    console.log(data);
Remove these console logs

2022-11-21 17:00 UTC, MaicolFreire001 commented on src/Components/Projects/Form/index.js
> +    console.log(data);
Done

2022-11-21 17:09 UTC, fede230298 commented on src/Components/Projects/validations.jsx
> +      'string.pattern.base': 'Project name should have letters only',
This regex does not mean this, the regex condition is to have at least one letter. It accepts numbers and special chars. But requires at least one letter out of the minimum three characters required

2022-11-21 17:10 UTC, fede230298 commented on src/Components/Projects/validations.jsx
> +      'string.pattern.base': 'Name should have letters only',
Same as above, it means it requires at least one letter

2022-11-21 17:10 UTC, fede230298 commented on src/Components/Projects/validations.jsx
> +    .regex(/^(?=.*[a-zA-Z].*)([\w\s\W]+)$/)
Same as above, it means it requires at least one letter

2022-11-21 17:11 UTC, fede230298 commented on src/Components/Projects/validations.jsx
> +      'string.min': 'Client name should have a minimum length of 2 characters',
Minimum length of 3 characters

2022-11-21 17:19 UTC, MaicolFreire001 commented on src/Components/Projects/validations.jsx
> +      'string.pattern.base': 'Project name should have letters only',
Solved

2022-11-21 17:19 UTC, MaicolFreire001 commented on src/Components/Projects/validations.jsx
> +      'string.pattern.base': 'Name should have letters only',
Solved

2022-11-21 17:19 UTC, MaicolFreire001 commented on src/Components/Projects/validations.jsx
> +      'string.pattern.base': 'Client name should have letters only',
Solved

2022-11-21 17:19 UTC, MaicolFreire001 commented on src/Components/Projects/validations.jsx
> +      'string.min': 'Client name should have a minimum length of 2 characters',
Solved

2022-11-21 17:28 UTC, JuliMonte5 approved these changes

2022-11-21 17:35 UTC, GonzaloAsencio approved these changes

2022-11-21 17:39 UTC, ProDIGGY-vinilos approved these changes

2022-11-21 17:46 UTC, fede230298 approved these changes

2022-11-21 19:24 UTC, sofihoj approved these changes

2022-11-21 19:31 UTC, MaicolFreire001 commented on src/Components/Projects/Form/index.js
> +    console.log(errors.endDate);
Done

2022-11-21 19:32 UTC, merged