BaSP-TG-44: Timesheets Screens
BaSP-a2022/ayom-b-trackgenix-app pull request #6
Opened 2022-11-02 01:05 UTC by JuliMonte5

Screens for Timesheets resource, with the following functionalities:

- See the list of timesheets saved in the DB.
- Edit a timesheet.
- Delete a timesheet.
- Add a new timesheet.

2022-11-02 15:04 UTC, ignacioaristo requested changes
1. Change al the component to a arrow functions (ES6).
2. The folder's name must be in camelCase.
3. We are not handle the success and error messages. For example when we delete a timesheet or create or update.

2022-11-02 15:04 UTC, ignacioaristo commented on src/Components/TimeSheets/Expand Modal/expandmodal.module.css
> +    background-color: white;
lets use hex convention.

2022-11-02 15:04 UTC, ignacioaristo commented on src/Components/TimeSheets/Form/index.js
> +      console.error(error);
Same with this console.error

2022-11-02 17:03 UTC, Ignacio-Sormani requested changes

2022-11-02 17:03 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Form/index.js
> +  timeSheetId.length == 24 ? (formSwitch = true) : (formSwitch = false);
Two comments related to this:
1) Don't use this kind of conditionals for functionality. It is normally use as conditions inside of return method. Use IFs
2) Don't add logic by itself in the component. It should be inside a function or useEffect.

2022-11-02 17:03 UTC, Ignacio-Sormani commented on src/Components/TimeSheets/Form/index.js
> +  let timeSheetId = path[path.length - 1];
If the value will change use it as a state. For example the formSwitch variable should be a state

2022-11-02 19:18 UTC, fede230298 commented on src/Components/TimeSheets/Form/index.js
> +      });
Manage the different status responses, both success and errors after performing the fetch

2022-11-03 03:16 UTC, Ignacio-Sormani approved these changes

2022-11-03 09:17 UTC, MaicolFreire001 requested changes

2022-11-03 09:17 UTC, MaicolFreire001 commented on src/Components/TimeSheets/index.js
> +      alert('Used deleted');
This alert message seems wrong

2022-11-03 09:17 UTC, MaicolFreire001 approved these changes
Seems good to me

2022-11-03 12:01 UTC, ignacioaristo approved these changes

2022-11-04 01:16 UTC, javierperezraffo approved these changes

2022-11-04 03:17 UTC, merged