BaSP-TG-45: Task entity
BaSP-a2022/ayom-b-trackgenix-app pull request #7
Opened 2022-11-02 01:26 UTC by MaicolFreire001

**List Tasks:**
• Retrieve Tasks from data base
• Created a Table view where the information is shown
• Added three buttons, to add, to delete and to edit tasks

**Delete Tasks**
• Implemented the functionality to delete a task from the list.

**Create a Task**
• Created the form view.
• Implemented the functionality to add a new task.

**Update a Task**
•  Implemented the functionality to update a task from the list.

2022-11-02 16:48 UTC, ignacioaristo requested changes
- Change all the component to arrow function (ES6)
- We are not handling the error and succes cases.

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/Form/index.js
> +  const [showPopUp, setPopUp] = useState(false);
In order to follow the good practices, this should be:
`  const [showPopUp, setShowPopUp] = useState(false);`

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/Form/index.js
> +  const [textPopUp, setText] = useState(false);
same here.

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/Form/index.js
> +        console.log(statusPopUp);
remove this console log

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/Form/index.js
> +      console.error(error);
create a local state to save this error, in order to remove the console.error

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/Modal/messageModal.js
> +    default: {
we should return 
default: return null
and then el brake. 
Because we are rendering components

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/index.js
> +      console.error(error);
the same error handling here.

2022-11-02 16:48 UTC, ignacioaristo commented on src/Components/Tasks/listItem.js
> +  const [showPopUp, setPopUp] = useState(false);
follow the good practice reported in the previous comment.

2022-11-02 19:33 UTC, fede230298 commented on src/Components/Tasks/Form/index.js
> +    if (taskId !== null) {
Wouldn't it be better if we check also the length of the id? To be sure that it matches the 24 char used in mongo's id

2022-11-02 19:40 UTC, fede230298 commented on src/Components/Tasks/listItem.js
> +    deleteTask(listTask._id);
Is this deleting the view before performing the delete on the data base?

2022-11-03 00:43 UTC, ProDIGGY-vinilos requested changes
Leave comments

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/Form/index.js
> +  const onSubmit = async (e) => {
Could add a blank line to respect the code as you have  above

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.listTable thead{
add space between thead and {

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.cancelButton {
add a blank line to seperate styles

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.addItem{
same as above, space between addItem and {

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.addItem label{
Same as above

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.addItem input{
Same as above

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.goBackButton{
Same as above

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.goBackButton:visited{
Same as above

2022-11-03 00:43 UTC, ProDIGGY-vinilos commented on src/Components/Tasks/tasks.module.css
> +.goBackButton:hover{
Add a blank line and a space between hover and {

2022-11-03 04:26 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +  const [showPopUp, setPopUp] = useState(false);
Done

2022-11-03 04:26 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +  const [textPopUp, setText] = useState(false);
done

2022-11-03 04:26 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +        console.log(statusPopUp);
done

2022-11-03 04:28 UTC, MaicolFreire001 commented on src/Components/Tasks/Modal/messageModal.js
> +    default: {
Done but without the brake because unreachable code

2022-11-03 04:28 UTC, MaicolFreire001 commented on src/Components/Tasks/listItem.js
> +  const [showPopUp, setPopUp] = useState(false);
Done

2022-11-03 04:29 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +    if (taskId !== null) {
I will be done directly in the server side, Its one of the tickets in the backlog

2022-11-03 04:30 UTC, MaicolFreire001 commented on src/Components/Tasks/listItem.js
> +    deleteTask(listTask._id);
Moved to delete it form the list after its deleted from the db

2022-11-03 04:31 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +  const onSubmit = async (e) => {
Done

2022-11-03 04:57 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.listTable thead{
Done

2022-11-03 04:57 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.cancelButton {
Done

2022-11-03 04:57 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.addItem{
Done

2022-11-03 04:58 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.addItem label{
Done

2022-11-03 04:58 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.addItem input{
Done

2022-11-03 04:58 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.goBackButton{
Done

2022-11-03 04:58 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.goBackButton:visited{
Done

2022-11-03 04:58 UTC, MaicolFreire001 commented on src/Components/Tasks/tasks.module.css
> +.goBackButton:hover{
Done

2022-11-03 05:13 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +      console.error(error);
I changed it to an alert like everybody elses. That's for server error only tho, all the other errors are handled in the catch.

2022-11-03 05:13 UTC, MaicolFreire001 commented on src/Components/Tasks/index.js
> +      console.error(error);
Same as above

2022-11-03 12:26 UTC, ignacioaristo commented on src/Components/Tasks/Modal/messageModal.js
> +    default: {
The break must exist.

2022-11-03 12:36 UTC, GonzaloAsencio approved these changes

2022-11-03 12:43 UTC, ignacioaristo requested changes

2022-11-03 12:43 UTC, ignacioaristo commented on src/Components/Tasks/Modal/messageModal.js
> +      return null;
add the `break;`

2022-11-04 01:22 UTC, Ignacio-Sormani requested changes

2022-11-04 01:22 UTC, Ignacio-Sormani commented on src/Components/Tasks/index.js
> +      response.status == 200 ? saveTasks(data.data) : alert(data.message);
Use if statement instead of conditional if you are executing logic. This kind of conditional is used for simpler stuff like data assignation

2022-11-04 02:28 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +      console.error(error);
I did

2022-11-04 02:35 UTC, MaicolFreire001 commented on src/Components/Tasks/index.js
> +      response.status == 200 ? saveTasks(data.data) : alert(data.message);
Done

2022-11-04 02:51 UTC, MaicolFreire001 commented on src/Components/Tasks/Form/index.js
> +    const params = new URLSearchParams(window.location.search);
Done

2022-11-04 02:51 UTC, MaicolFreire001 commented on src/Components/Tasks/listItem.js
> +        <a href={`task-form?id=${listTask._id}`}>
Done

2022-11-04 03:20 UTC, Ignacio-Sormani approved these changes

2022-11-04 10:50 UTC, javierperezraffo approved these changes

2022-11-04 14:29 UTC, ProDIGGY-vinilos approved these changes

2022-11-04 14:56 UTC, ignacioaristo approved these changes

2022-11-04 14:56 UTC, merged