BaSP-TG-46:employee entity
BaSP-a2022/ayom-b-trackgenix-app pull request #8
Opened 2022-11-02 01:42 UTC by aletiscornia

1. List all the employees:

 - Retrieve the data from the data base and list all the employees.
 - Create a list view where each item has a button to add, update and delete.

2. Delete an employee:

 - Delete an employee from the list.

3. Create an employee:
 -  Create the form view.
 -  Create a new employee.

4. Update an employee:

 - Update an employee from the list.

2022-11-02 01:53 UTC, GonzaloAsencio commented on src/Components/Employees/index.js
> +// import Employee from './Employee';
Delete this comment

2022-11-02 01:54 UTC, GonzaloAsencio commented on src/Components/Employees/index.js
> +    // eslint-disable-next-line no-undef
Delete this comment

2022-11-02 01:55 UTC, GonzaloAsencio commented on src/Components/Employees/FormAddEmployee.js
> +// import Modal from './modal/modal';
Delete this comment

2022-11-02 16:14 UTC, Ignacio-Sormani commented on src/Components/Employees/FormAddEmployee.js
> +        setTimeout(() => {
Remove set timeout

2022-11-02 16:16 UTC, Ignacio-Sormani commented on src/Components/Employees/index.js
>    const [employees, saveEmployees] = useState([]);
Use setEmployees instead of saveEmployees for the name of the setState

2022-11-02 16:16 UTC, Ignacio-Sormani commented on src/Components/Employees/index.js
> +    fetch(`${process.env.REACT_APP_API_URL}/employees`)
Use async await

2022-11-02 16:16 UTC, Ignacio-Sormani commented on src/Components/Employees/index.js
> +    saveEmployees(employees.filter((e) => e._id != id));
Use !== instead of !=

2022-11-02 16:18 UTC, Ignacio-Sormani commented on src/Components/Employees/modal/modal.js
> +function Modal(props) {
Destructure props:
`function Modal({openModal, closeModal, id, ...}) {`

2022-11-02 16:19 UTC, Ignacio-Sormani commented on src/Components/Employees/FormAddEmployee.js
> +const FormAddEmployee = () => {
Use 'EmployeeForm' as name of the component

2022-11-03 05:20 UTC, aletiscornia commented on src/Components/Employees/index.js
> +    saveEmployees(employees.filter((e) => e._id != id));
fixed

2022-11-03 05:38 UTC, aletiscornia commented on src/Components/Employees/FormAddEmployee.js
> +const FormAddEmployee = () => {
fixed

2022-11-03 05:39 UTC, aletiscornia commented on src/Components/Employees/index.js
>    const [employees, saveEmployees] = useState([]);
fixed

2022-11-03 12:37 UTC, aletiscornia commented on src/Components/Employees/index.js
> +    fetch(`${process.env.REACT_APP_API_URL}/employees`)
fixed

2022-11-03 13:20 UTC, aletiscornia commented on src/Components/Employees/FormAddEmployee.js
> +    fetch(`${process.env.REACT_APP_API_URL}/employees${url}`, requestOptions).then((response) => {
fixed

2022-11-03 14:56 UTC, aletiscornia commented on src/Components/Employees/FormAddEmployee.js
> +        setTimeout(() => {
fixed

2022-11-03 14:56 UTC, aletiscornia commented on package.json
> +    "react-scripts": "^5.0.1",
fixed

2022-11-03 15:52 UTC, aletiscornia commented on src/Components/Employees/modal/modal.js
> +function Modal(props) {
fixed

2022-11-04 01:24 UTC, Ignacio-Sormani requested changes

2022-11-04 01:24 UTC, Ignacio-Sormani commented on src/Components/Employees/EmployeeForm.js
> +    console.log('asdasd');
Remove console.log

2022-11-04 18:42 UTC, Ignacio-Sormani commented
Please resolve conflicts so QA can test and merge afterwards

2022-11-04 19:09 UTC, Ignacio-Sormani approved these changes

2022-11-04 19:12 UTC, MaicolFreire001 approved these changes
SGTM

2022-11-04 19:24 UTC, javierperezraffo approved these changes

2022-11-04 19:29 UTC, merged