BaSP-TG-42: SuperAdmin entity
BaSP-a2022/ayom-b-trackgenix-app pull request #9
Opened 2022-11-02 01:55 UTC by ProDIGGY-vinilos

1. List all the super admin

- Retrieve the data from the data base and list all the super admin.
- Create a list view where each item has a button to add, update and delete.

2. Delete an super admin

- Delete a super admin from the list.

3.Update an super admin

- Update a super admin from the list.

2022-11-02 01:57 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/super-admins.module.css
> +}
Add a space here!

2022-11-02 01:57 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/index.js
> +// import DeleteButton from './Delete Button/deleteButton';
delete this comment

2022-11-02 01:58 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/super-admins.module.css
> +table{
Add a space here!

2022-11-02 01:58 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/super-admins.module.css
>  }
Add a space here!

2022-11-02 01:58 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/super-admins.module.css
>    display: flex;
Add a space here!

2022-11-02 01:58 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/super-admins.module.css
> +.btn{
Add a space here!

2022-11-02 01:59 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/Form/index.js
> +    let sAdminId = path[path.length - 1];
you can change "sAdminId" for "**superAdminId**"

2022-11-02 02:04 UTC, GonzaloAsencio commented on src/Components/SuperAdmins/Form/form.module.css
> +.container{
put an empty line between each style.

2022-11-02 16:03 UTC, Ignacio-Sormani requested changes

2022-11-02 16:03 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/Form/index.js
> +        <h3>Super admin edit/create</h3>
You can use a conditional to write 'Super admin edit' or 'Super admin create'

2022-11-02 16:03 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/Modal/modal.module.css
> +.modal {
Leave one blank line between css blocks

2022-11-02 16:03 UTC, Ignacio-Sormani commented on src/Components/SuperAdmins/index.js
> +  const [superAdmins, saveSuperAdmins] = useState([]);
Change the name of the setState function to 'setSuperAdmins'

2022-11-02 19:48 UTC, fede230298 commented on src/Components/SuperAdmins/Form/index.js
> +        updateDeleteSAdmin('PUT', url);
Should redirect to SuperAdmin page after a successful request

2022-11-02 19:49 UTC, fede230298 commented on src/Components/SuperAdmins/Form/index.js
> +        updateDeleteSAdmin('POST', url);
Same comment as above

2022-11-02 19:50 UTC, fede230298 commented on src/Components/SuperAdmins/ListSuperAdmins/index.js
> +    onDeleteSuperAdmin(sAdmin._id);
Should check the success response before actually deleting the view

2022-11-03 03:01 UTC, Ignacio-Sormani approved these changes

2022-11-03 04:18 UTC, GonzaloAsencio approved these changes

2022-11-04 01:14 UTC, javierperezraffo approved these changes

2022-11-04 03:14 UTC, merged